name: Super-Fast and Resilient Add Item

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Item Code/Title'
        required: true
        type: string
      english_description:
        description: 'English Description'
        required: true
        type: string
      persian_description:
        description: 'Persian Description'
        required: true
        type: string
      image:
        description: 'Image Filename'
        required: true
        type: string

jobs:
  fast_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # ما به توکن نیاز داریم تا بتوانیم push کنیم
          token: ${{ secrets.GITHUB_TOKEN }} 

      - name: Atomically Update and Push
        env:
          ITEM_TITLE: ${{ github.event.inputs.title }}
          ITEM_DESC_EN: ${{ github.event.inputs.english_description }}
          ITEM_DESC_FA: ${{ github.event.inputs.persian_description }}
          ITEM_IMAGE: ${{ github.event.inputs.image }}
        run: |
          set -e

          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # حلقه تلاش مجدد با منطق جدید
          for i in {1..5}
          do
            # ۱. دریافت آخرین اطلاعات از سرور (بدون تغییر فایل‌های محلی)
            git fetch origin main

            # ۲. بازنشانی کامل به آخرین نسخه روی سرور.
            # این کار هرگونه کامیت محلی ناموفق یا تداخل را پاک می‌کند.
            git reset --hard origin/main

            # ۳. حالا که روی آخرین نسخه هستیم، تغییرات خود را دوباره اعمال می‌کنیم
            DATA_FILE="Data.json"
            IMAGE_RAW_URL="https://raw.githubusercontent.com/${{ github.repository }}/main/Images/${ITEM_IMAGE}"
            
            add_newline_before_words() {
              local input="$1"
              local words=("Ring" "Silver" "Weight" "Type" "مديل" "نوع" "عيار" "الوزن")
              for word in "${words[@]}"; do
                input=$(echo "$input" | sed "s/\b$word\b/\n$word/g")
              done
              echo "$input"
            }

            FORMATTED_DESC_EN=$(add_newline_before_words "${ITEM_DESC_EN}")
            FORMATTED_DESC_FA=$(add_newline_before_words "${ITEM_DESC_FA}")
            
            json_content=$(cat $DATA_FILE)
            new_item=$(jq -n --arg title "$ITEM_TITLE" --arg englishDescription "$FORMATTED_DESC_EN" --arg persianDescription "$FORMATTED_DESC_FA" --arg image "$IMAGE_RAW_URL" '{title: $title, englishDescription: $englishDescription, persianDescription: $persianDescription, image: $image}')
            new_json=$(echo "$json_content" | jq ".items += [$new_item]")
            echo "$new_json" | jq '.' > $DATA_FILE

            # ۴. کامیت جدید را ایجاد و تلاش برای push می‌کنیم
            git add $DATA_FILE
            git commit -m "Added new item: $ITEM_TITLE"
            
            # اگر پوش موفق بود، با موفقیت خارج شو
            if git push; then
              echo "Push successful on attempt $i!"
              exit 0
            fi
            
            # اگر پوش شکست خورد، یعنی یک نفر دیگر در همین لحظه پوش کرده است.
            # حلقه تکرار می‌شود و ما دوباره از آخرین نسخه شروع می‌کنیم.
            echo "Push failed on attempt $i. Another process may have pushed. Retrying..."
            sleep $(shuf -i 1-3 -n 1) # یک تا سه ثانیه به صورت تصادفی صبر کن
          done

          echo "Error: Could not push changes after multiple attempts."
          exit 1
