name: Add Item to JSON

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title of the item'
        required: true
        type: string
      english_description:
        description: 'Description in English (Single-line input, auto-formats)'
        required: true
        type: string
      persian_description:
        description: 'Description in Persian (Single-line input, auto-formats)'
        required: true
        type: string
      image:
        description: 'Image filename (from Images folder)'
        required: true
        type: string

jobs:
  update_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Get raw URL of selected image
      id: image_url
      run: echo "image_url=https://raw.githubusercontent.com/${{ github.repository }}/main/Images/${{ github.event.inputs.image }}" >> $GITHUB_ENV

    - name: Format descriptions and add item to data.json
      run: |
        add_newline_before_words() {
          local input="$1"
          local words_to_add_newline=("Ring" "Silver" "Weight" "Type" "مديل" "نوع" "عيار" "الوزن")
          for word in "${words_to_add_newline[@]}"; do
            input=$(echo "$input" | sed "s/\b$word\b/\n$word/g")
          done
          echo "$input"
        }
        
        ITEM_TITLE="${{ github.event.inputs.title }}"
        ITEM_DESC_EN=$(add_newline_before_words "${{ github.event.inputs.english_description }}")
        ITEM_DESC_FA=$(add_newline_before_words "${{ github.event.inputs.persian_description }}")
        IMAGE_URL="https://raw.githubusercontent.com/${{ github.repository }}/main/Images/${{ github.event.inputs.image }}"
        
        DATA_FILE="Data.json"
        new_item=$(jq -n --arg title "$ITEM_TITLE" \
                         --arg englishDescription "$ITEM_DESC_EN" \
                         --arg persianDescription "$ITEM_DESC_FA" \
                         --arg image "$IMAGE_URL" \
                         '{title: $title, englishDescription: $englishDescription, persianDescription: $persianDescription, image: $image}')
        
        jq ".items += [$new_item]" "$DATA_FILE" | tee "$DATA_FILE"

    - name: Commit changes
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "Your Name"
        git add Data.json
        git commit -m "Added new item: ${{ github.event.inputs.title }}"
        git push
