name: Add Item to JSON

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title of the item'
        required: true
        type: string
      description:
        description: 'Description of the item (supports multiple lines)'
        required: true
        type: string
      image:
        description: 'Image filename (from Images folder)'
        required: true
        type: string

jobs:
  update_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get list of image files
      id: image_list
      run: |
        echo "Fetching list of image files in the Images folder..."
        IMAGE_FILES=$(ls Images)
        echo "::set-output name=images::$(echo $IMAGE_FILES | tr ' ' '\n')"

    - name: Get raw URL of selected image
      id: image_url
      run: |
        IMAGE_NAME="${{ github.event.inputs.image }}"
        IMAGE_RAW_URL="https://raw.githubusercontent.com/${{ github.repository }}/main/Images/${IMAGE_NAME}"
        echo "::set-output name=image_url::$IMAGE_RAW_URL"

    - name: Add item to data.json
      run: |
        ITEM_TITLE="${{ github.event.inputs.title }}"
        ITEM_DESC="${{ github.event.inputs.description }}"
        # Escape newlines in the description for JSON compatibility
        ITEM_DESC=$(echo "$ITEM_DESC" | sed ':a;N;$!ba;s/\n/\\n/g')
        ITEM_IMG="${{ steps.image_url.outputs.image_url }}"

        # Read the existing data.json
        DATA_FILE="Data.json"
        json_content=$(cat $DATA_FILE)

        # Add the new item with the image URL
        new_item="{\"title\":\"$ITEM_TITLE\",\"description\":\"$ITEM_DESC\",\"image\":\"$ITEM_IMG\"}"

        # Append the new item to the JSON array
        new_json=$(echo "$json_content" | jq ".items += [$new_item]")

        # Write the updated JSON to the file
        echo "$new_json" > $DATA_FILE

    - name: Commit changes
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "Your Name"
        git add Data.json
        git commit -m "Added new item: ${{ github.event.inputs.title }}"
        git push
