name: Add Item to JSON

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title of the item'
        required: true
        type: string
      english_description:
        description: 'Description in English (Single-line input, auto-formats)'
        required: true
        type: string
      persian_description:
        description: 'Description in Persian (Single-line input, auto-formats)'
        required: true
        type: string
      image:
        description: 'Image filename (from Images folder)'
        required: true
        type: string

jobs:
  update_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get raw URL of selected image
      id: image_url
      run: |
        IMAGE_NAME="${{ github.event.inputs.image }}"
        IMAGE_RAW_URL="https://raw.githubusercontent.com/${{ github.repository }}/main/Images/${IMAGE_NAME}"
        echo "image_url=$IMAGE_RAW_URL" >> $GITHUB_ENV

    - name: Format descriptions and add item to data.json
      run: |
        ITEM_TITLE="${{ github.event.inputs.title }}"

        extract_and_format() {
          local input="$1"
          local formatted_output=""
          
          while IFS= read -r line; do
            if [[ "$line" =~ ^([^:]+):(.+)$ ]]; then
              key="${BASH_REMATCH[1]}"
              value="${BASH_REMATCH[2]}"
              formatted_output+="$key: $value"$'\n'
            else
              formatted_output+="$line"$'\n'
            fi
          done <<< "$(echo "$input" | tr '،' ',' | tr '؛' ';')" 

          echo "$formatted_output"
        }

        ITEM_DESC_EN=$(extract_and_format "${{ github.event.inputs.english_description }}")
        ITEM_DESC_FA=$(extract_and_format "${{ github.event.inputs.persian_description }}")
        ITEM_IMG="$image_url"

        DATA_FILE="Data.json"
        json_content=$(cat $DATA_FILE)

        new_item=$(
          jq -n --arg title "$ITEM_TITLE" \
                --arg englishDescription "$ITEM_DESC_EN" \
                --arg persianDescription "$ITEM_DESC_FA" \
                --arg image "$ITEM_IMG" \
                '{title: $title, englishDescription: $englishDescription, persianDescription: $persianDescription, image: $image}'
        )

        new_json=$(echo "$json_content" | jq ".items += [$new_item]")
        echo "$new_json" | jq '.' > $DATA_FILE

    - name: Commit changes
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "Your Name"
        git add Data.json
        git commit -m "Added new item: ${{ github.event.inputs.title }}"
        git push
