name: Add Item to JSON

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title of the item'
        required: true
        type: string
      description:
        description: 'Description of the item (supports multiple lines)'
        required: true
        type: string
      image:
        description: 'Image filename (from Images folder)'
        required: true
        type: string

jobs:
  update_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get raw URL of selected image
      id: image_url
      run: |
        IMAGE_NAME="${{ github.event.inputs.image }}"
        IMAGE_RAW_URL="https://raw.githubusercontent.com/${{ github.repository }}/main/Images/${IMAGE_NAME}"
        echo "::set-output name=image_url::$IMAGE_RAW_URL"

    - name: Add item to data.json
      run: |
        ITEM_TITLE="${{ github.event.inputs.title }}"
        ITEM_DESC="${{ github.event.inputs.description }}"
        ITEM_IMG="${{ steps.image_url.outputs.image_url }}"

        # Read the existing Data.json
        DATA_FILE="Data.json"
        json_content=$(cat $DATA_FILE)

        # Format the new item with the description on multiple lines
        new_item=$(
          jq -n --arg title "$ITEM_TITLE" \
                --arg description "$ITEM_DESC" \
                --arg image "$ITEM_IMG" \
                '{title: $title, description: $description, image: $image}'
        )

        # Append the new item to the JSON array
        new_json=$(echo "$json_content" | jq ".items += [$new_item]")

        # Write the updated JSON to the file
        echo "$new_json" | jq '.' > $DATA_FILE

    - name: Commit changes
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "Your Name"
        git add Data.json
        git commit -m "Added new item: ${{ github.event.inputs.title }}"
        git push
