name: 1. Create Item Request

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title of the item'
        required: true
        type: string
      english_description:
        description: 'Description in English (Single-line, auto-formats)'
        required: true
        type: string
      persian_description:
        description: 'Description in Persian (Single-line, auto-formats)'
        required: true
        type: string
      image:
        description: 'Image filename (from Images folder)'
        required: true
        type: string

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Issue for the new item
        uses: dacbd/create-issue-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "New Item Request: ${{ github.event.inputs.title }}"
          body: |
            ### New Item Details

            **Title:** `${{ github.event.inputs.title }}`
            **English Description:** `${{ github.event.inputs.english_description }}`
            **Persian Description:** `${{ github.event.inputs.persian_description }}`
            **Image Filename:** `${{ github.event.inputs.image }}`

            ---
            *This request will be processed automatically.*
          labels: new-item-request # این برچسب کلید اصلی کار ماست
