name: Jarah_Submit_Form

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title of the item'
        required: true
        type: string
      english_description:
        description: 'Description in English (Single-line input, auto-formats)'
        required: true
        type: string
      persian_description:
        description: 'Description in Persian (Single-line input, auto-formats)'
        required: true
        type: string
      image:
        description: 'Image filename (from Images folder)'
        required: true
        type: string

jobs:
  update_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to ensure we can pull remote changes

      - name: Get raw URL of selected image
        id: image_url
        run: |
          IMAGE_NAME="${{ github.event.inputs.image }}"
          IMAGE_RAW_URL="https://raw.githubusercontent.com/${{ github.repository }}/main/Images/${IMAGE_NAME}"
          echo "image_url=$IMAGE_RAW_URL" >> $GITHUB_ENV

      - name: Format descriptions and add item to jarah.json
        run: |
          ITEM_TITLE="${{ github.event.inputs.title }}"

          add_newline_before_words() {
            local input="$1"
            local words_to_add_newline=("Ring" "Silver" "Weight" "Type" "مديل" "نوع" "عيار" "الوزن")  # Add words here that should trigger a newline before them

            for word in "${words_to_add_newline[@]}"; do
              input=$(echo "$input" | sed "s/\b$word\b/\n$word/g")
            done

            echo "$input"
          }

          ITEM_DESC_EN=$(add_newline_before_words "${{ github.event.inputs.english_description }}")
          ITEM_DESC_FA=$(add_newline_before_words "${{ github.event.inputs.persian_description }}")
          ITEM_IMG="$image_url"

          DATA_FILE="Data Folder/jarah.json"
          json_content=$(cat "$DATA_FILE")

          new_item=$(
            jq -n --arg title "$ITEM_TITLE" \
                  --arg englishDescription "$ITEM_DESC_EN" \
                  --arg persianDescription "$ITEM_DESC_FA" \
                  --arg image "$ITEM_IMG" \
                  '{title: $title, englishDescription: $englishDescription, persianDescription: $persianDescription, image: $image}'
          )

          # Add the new item to the existing JSON file
          new_json=$(echo "$json_content" | jq ".items += [$new_item]")
          echo "$new_json" | jq '.' > "$DATA_FILE"

      - name: Commit and push changes
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git add "Data Folder/jarah.json"
          git commit -m "Added new item: ${{ github.event.inputs.title }}" || echo "No changes to commit"
          # Pull remote changes and rebase your commit on top
          git pull origin main --rebase
          git push
